// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCommon.DataModel;

namespace WebApiCommon.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20200129094806_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiCommon.DataModel.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HiveId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HiveId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Name 1",
                            Code = "12c25"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Name 2",
                            Code = "4255kg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Name 3",
                            Code = "82ds5"
                        });
                });

            modelBuilder.Entity("WebApiCommon.DataModel.Hive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address 1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address 2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Address 3"
                        });
                });

            modelBuilder.Entity("WebApiCommon.DataModel.Category", b =>
                {
                    b.HasOne("WebApiCommon.DataModel.Hive", "Hive")
                        .WithMany()
                        .HasForeignKey("HiveId");
                });
#pragma warning restore 612, 618
        }
    }
}
